@startuml domain_model
skinparam PackageStyle rectangle

package ユーザー集約 {
    object ユーザー {
        ID
        名前
        メールアドレス
        パスワード
        自己紹介
    }
    object スキル {
        ID
        ユーザーID
        タグID
        評価
        年数
    }
    object 経歴 {
        ID
        ユーザーID
        経歴詳細
        西暦from
        西暦to
    }
}

note left of ユーザー
    * 名前：255文字以内(ユニーク)
    * メールアドレス：255文字以内
    * パスワード：12文字以上,英数字それぞれ最低1文字以上
    * 自己紹介：任意項目
end note

note bottom of スキル
    * タグ名：選択式
    * 評価：1~5
    * 年数：０以上のint型(5年まで)
end note

note bottom of 経歴
    * 詳細：1000字以内
    * 西暦from：1970年以上のint型
    * 西暦to：1970年以上のint型、西暦fromよりも大きい数字
end note
ユーザー "1" -down- "1..n" スキル
ユーザー "1" -down- "0..1" 経歴

package メンター募集集約 {
    object メンター募集 {
        ID
        タイトル
        カテゴリID
        相談形式
        相談方式
        ディスクリプション
        予算
        応募期間
        ステータス
        タグ
    }
}

note left of メンター募集 
    * タイトル: 255文字以内
    * カテゴリ：以下から1つ選択
        * プログラミング
        * マーケティング
        * デザイン
        * ライティング
        * 動画・映像
        * ビジネス
        * 語学
        * ライフスタイル
    * 相談形式
        * 単発
        * 継続
    * 相談方式
        * チャット
        * ビデオ通話
    * ディスクリプション：2000文字以内
    * 予算：from円~to円
        * 1000円以上の数値
    * 応募期間
        * 1日単位
        * 最大14日後まで可能
    * ステータス：公開or中止
end note
メンター募集 "1" -down- "1..n" ユーザー

package プラン作成集約 {
    object プラン {
        ID
        タイトル
        カテゴリID
        タグID
        内容
        ステータス
        相談形式
        金額
        相談方式
    }
}

note left of プラン 
    * タイトル: 255文字以内
    * カテゴリ(1つ)
        * プログラミング
        * マーケティング
        * デザイン
        * ライティング
        * 動画・映像
        * ビジネス
        * 語学
        * ライフスタイル
    * タグ(5個まで)
        * 選択式
    * 内容：2000文字以内
    * ステータス：公開or中止
    * 相談形式
        * 単発
        * 継続
    * 相談方式：チャットorビデオ電話
end note
メンター募集 "1" -down- "1" プラン

package プラン契約集約 {
    object メンター募集に提案 {
        ID
        メンター募集ID
        ユーザーID
        提案内容
    }
    object プラン契約リクエストを送信 {
        ID
        プランID
        ユーザーID
        メッセージ
    }
    object プランへの契約を承認 {
        ID
        プランID
        ユーザーID
        メッセージ
    }
}

note bottom of メンター募集に提案 
    * 提案内容: 2000文字以内
    * 提案できるのはスキルを5個以上持つユーザのみ
end note

note bottom of プラン契約リクエストを送信 
    * メッセージ: 500文字以内
end note

note left of プランへの契約を承認
    * メッセージ: 500文字以内
end note

メンター募集 "1" -left- "1..n" メンター募集に提案
プラン "1" -left- "1..n" プラン契約リクエストを送信
プラン契約リクエストを送信 "1" -left- "0..1" プランへの契約を承認


@enduml

' 名前 "1" left* "1" 候補者
' ペンダント "1" down* "1" 候補者
' キューブ "0..8" down* "1" ペンダント





' モデル図の書き方参考：https://tech.contracts.co.jp/entry/2020/10/16/150605
' 「集約」について参考：https://www.youtube.com/watch?v=Hn4EAXYBl8c